# Generated by Django 6.0.4 on 2026-05-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturnDetail',
            fields=[
                ('srd_rid', models.AutoField(primary_key=True, serialize=False)),
                ('srd_sr_rid', models.IntegerField()),
                ('srd_item_rid', models.IntegerField()),
                ('srd_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('srd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('srd_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'sale_return_detail',
                'ordering': ['srd_rid'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnHeader',
            fields=[
                ('sr_rid', models.AutoField(primary_key=True, serialize=False)),
                ('sr_status', models.CharField(default='Active', max_length=12)),
                ('sr_sale_return_no', models.CharField(max_length=50, unique=True)),
                ('sr_sale_return_date', models.DateField()),
                ('sr_notes', models.CharField(blank=True, max_length=520, null=True)),
                ('sr_counter_sale', models.BooleanField(default=False)),
                ('sr_acc_rid', models.IntegerField()),
                ('sr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sr_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sr_net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sr_created_date', models.DateTimeField(auto_now_add=True)),
                ('sr_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sale_return_header',
                'ordering': ['-sr_rid'],
            },
        ),
    ]
