# Generated by Django 6.0.4 on 2026-05-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasereturnDetail',
            fields=[
                ('prd_rid', models.AutoField(primary_key=True, serialize=False)),
                ('prd_bh_rid', models.IntegerField()),
                ('prd_item_rid', models.IntegerField()),
                ('prd_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prd_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'purchasereturn_detail',
                'ordering': ['prd_rid'],
            },
        ),
        migrations.CreateModel(
            name='PurchasereturnHeader',
            fields=[
                ('pr_rid', models.AutoField(primary_key=True, serialize=False)),
                ('pr_status', models.CharField(default='Active', max_length=12)),
                ('pr_bill_no', models.CharField(max_length=50, unique=True)),
                ('pr_bill_date', models.DateField()),
                ('pr_notes', models.CharField(blank=True, max_length=520, null=True)),
                ('pr_counter_sale', models.BooleanField(default=False)),
                ('pr_acc_rid', models.IntegerField()),
                ('pr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pr_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pr_net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pr_created_date', models.DateTimeField(auto_now_add=True)),
                ('pr_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchasereturn_header',
                'ordering': ['-pr_rid'],
            },
        ),
    ]
