# Generated by Django 6.0.4 on 2026-05-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasereturn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchasereturndetail',
            table='purchase_return_detail',
        ),
        migrations.AlterModelTable(
            name='purchasereturnheader',
            table='purchase_return_header',
        ),
    ]
