# Generated by Django 6.0.4 on 2026-05-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasereturn', '0002_alter_purchasereturndetail_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereturnheader',
            old_name='pr_bill_date',
            new_name='pr_purchase_return_date',
        ),
        migrations.RenameField(
            model_name='purchasereturnheader',
            old_name='pr_bill_no',
            new_name='pr_purchase_return_no',
        ),
    ]
