# Generated by Django 6.0.4 on 2026-05-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasereturn', '0003_rename_pr_bill_date_purchasereturnheader_pr_purchase_return_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereturnheader',
            old_name='pr_counter_sale',
            new_name='pr_counter_purchase',
        ),
    ]
