# Generated by Django 6.0.4 on 2026-05-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasereturn', '0004_rename_pr_counter_sale_purchasereturnheader_pr_counter_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereturndetail',
            old_name='prd_bh_rid',
            new_name='prd_pr_rid',
        ),
    ]
