# Generated by Django 6.0.4 on 2026-05-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('pd_rid', models.AutoField(primary_key=True, serialize=False)),
                ('pd_bh_rid', models.IntegerField()),
                ('pd_item_rid', models.IntegerField()),
                ('pd_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pd_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'purchase_detail',
                'ordering': ['pd_rid'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseHeader',
            fields=[
                ('ph_rid', models.AutoField(primary_key=True, serialize=False)),
                ('ph_status', models.CharField(default='Active', max_length=12)),
                ('ph_bill_no', models.CharField(max_length=50, unique=True)),
                ('ph_bill_date', models.DateField()),
                ('ph_notes', models.CharField(blank=True, max_length=520, null=True)),
                ('ph_counter_sale', models.BooleanField(default=False)),
                ('ph_acc_rid', models.IntegerField()),
                ('ph_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ph_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ph_net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ph_created_date', models.DateTimeField(auto_now_add=True)),
                ('ph_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchase_header',
                'ordering': ['-ph_rid'],
            },
        ),
    ]
