# Generated by Django 6.0.4 on 2026-05-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='pd_bh_rid',
            new_name='pd_ph_rid',
        ),
        migrations.RenameField(
            model_name='purchaseheader',
            old_name='ph_bill_date',
            new_name='ph_purchase_date',
        ),
        migrations.RenameField(
            model_name='purchaseheader',
            old_name='ph_bill_no',
            new_name='ph_purchase_no',
        ),
    ]
