# Generated by Django 6.0.4 on 2026-04-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('bd_rid', models.AutoField(primary_key=True, serialize=False)),
                ('bd_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bd_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bd_total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'bill_detail',
            },
        ),
        migrations.CreateModel(
            name='BillHeader',
            fields=[
                ('bh_rid', models.AutoField(primary_key=True, serialize=False)),
                ('bh_bill_no', models.CharField(max_length=50, unique=True)),
                ('bh_bill_date', models.DateField()),
                ('bh_notes', models.CharField(blank=True, max_length=120, null=True)),
                ('bh_counter_sale', models.BooleanField(default=False)),
                ('bh_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'bill_header',
            },
        ),
    ]
