# Generated by Django 6.0.4 on 2026-05-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='bd_bh_rid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billdetail',
            name='bd_item_rid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billheader',
            name='bh_acc_rid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
