# Generated by Django 6.0.4 on 2026-05-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_billdetail_bd_bh_rid_billdetail_bd_item_rid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billdetail',
            options={'ordering': ['bd_rid']},
        ),
        migrations.AlterModelOptions(
            name='billheader',
            options={'ordering': ['-bh_rid']},
        ),
        migrations.AddField(
            model_name='billheader',
            name='bh_created_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billheader',
            name='bh_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billheader',
            name='bh_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='billheader',
            name='bh_net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billheader',
            name='bh_status',
            field=models.CharField(default='Active', max_length=12),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='bd_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='bd_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='bd_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='billheader',
            name='bh_notes',
            field=models.CharField(blank=True, max_length=520, null=True),
        ),
    ]
