# Generated by Django 6.0.4 on 2026-05-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_rid', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=60, unique=True)),
                ('item_code', models.CharField(max_length=10, unique=True)),
                ('item_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('item_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_stk', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
