# Generated by Django 6.0.4 on 2026-05-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_display_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
